services:
  tutoeasydb:
    image: mysql:latest
    container_name: tutoeasydb
    restart: always
    ports:
      - ${LOCAL_EXPOSED_PORT}:${MYSQL_EXPOSED_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: $[MYSQL_RANDOM_ROOT_PASSWORD}
    volumes:
      - ./tutoeasy-mysql:/var/lib/mysql
